
spring:
# config profile active
  profiles:
    active: dev
    
  application:
    name: appointmentManagement

  servlet:
    multipart:
      max-file-size: 5MB    # Tamaño máximo permitido para un archivo
      max-request-size: 5MB # Tamaño máximo permitido para toda la solicitud (puede incluir múltiples archivos)


#config server    
server:
  servlet:
    context-path: /appointment-management/api/v1
    
security:
  jwt:
    token:
      secret-key: ${JWT_SECRET}
      expiration-time-min: 1440


cloudinary:
  cloudName: ${CLOUDINARY_CLOUD_NAME}
  apiKey: ${CLOUDINARY_API_KEY}
  apiSecret: ${CLOUDINARY_API_SECRET}

