
spring:
# config profile active
  profiles:
    active: dev
    
  application:
    name: appointmentManagement


#config server    
server:
  servlet:
    context-path: /appointment-management/api/v1
    
security:
  jwt:
    token:
      secret-key: ${JWT_SECRET}
      expiration-time-min: 1440
